spring:
  datasource:
    url: jdbc:mysql://localhost:3306/algafoodapi?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
  jackson:
    deserialization:
      fail-on-ignored-properties: true
      fail-on-unknown-properties: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false