CREATE TABLE ITEMPEDIDO (
	Id BIGINT NOT NULL AUTO_INCREMENT,
	Quantidade INT NOT NULL,
	Preco_Unitario FLOAT NOT NULL,
	Preco_Total FLOAT NOT NULL,
	Observacao VARCHAR(150) NOT NULL,
	Pedido_Id BIGINT NOT NULL,
	Produto_Id BIGINT NOT NULL,
	PRIMARY KEY (Id),
	FOREIGN KEY FK_PEDIDO_ID (Pedido_Id) REFERENCES PEDIDO (ID),
	FOREIGN KEY FK_PRODUTO_ID (Produto_Id) REFERENCES PRODUTO (ID)
)
